capture = wlr
encoder = nvenc
fec_percentage = 20
locale = es
min_log_level = 2
output_name = HEADLESS-1
sunshine_name = Sunshine PC
global_prep_cmd = [{"do":"~/.local/bin/sunshine-connect.sh","undo":"~/.local/bin/sunshine-disconnect.sh","elevated":false}]
